spring:
  application:
    name: allobank-split-bill

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/allobank_split_bill}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 4110

app:
  github-username: ${GITHUB_USERNAME:ilhamhafizha}